package firma;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import firma.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2017.07.19 16:46:28 // Generated by ComTest
 *
 */
public class TerapeuttiTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi73 */
  @Test
  public void testRekisteroi73() {    // Terapeutti: 73
    Terapeutti greta1 = new Terapeutti(); 
    assertEquals("From: Terapeutti line: 75", 0, greta1.getTunnusNro()); 
    greta1.rekisteroi(); 
    Terapeutti greta2 = new Terapeutti(); 
    greta2.rekisteroi(); 
    int n1 = greta1.getTunnusNro(); 
    int n2 = greta2.getTunnusNro(); 
    assertEquals("From: Terapeutti line: 81", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString118 */
  @Test
  public void testToString118() {    // Terapeutti: 118
    Terapeutti terapeutti = new Terapeutti(); 
    terapeutti.parse("   1   |  2  |   Jorg Jonkainen  | Musiikkiterapia | 2x45 "); 
    assertEquals("From: Terapeutti line: 121", "1|2|Jorg Jonkainen|Musiikkiterapia|2x45", terapeutti.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse135 */
  @Test
  public void testParse135() {    // Terapeutti: 135
    Terapeutti terapeutti = new Terapeutti(); 
    terapeutti.parse("   1   |  2  |   Jorg Jonkainen | Musiikkiterapia | 2x45 "); 
    assertEquals("From: Terapeutti line: 138", 2, terapeutti.getAsiakasNro()); 
    assertEquals("From: Terapeutti line: 139", "1|2|Jorg Jonkainen|Musiikkiterapia|2x45", terapeutti.toString()); 
    terapeutti.rekisteroi(); 
    int n = terapeutti.getTunnusNro(); 
    terapeutti.parse(""+(n+20)); 
    terapeutti.rekisteroi(); 
    assertEquals("From: Terapeutti line: 144", n+20+1, terapeutti.getTunnusNro()); 
    assertEquals("From: Terapeutti line: 145", "" + (n+20+1) + "|2|Jorg Jonkainen|Musiikkiterapia|2x45", terapeutti.toString()); 
  } // Generated by ComTest END
}